import type { PlatformUserRecord } from "@/lib/platform-users-db";
import type { BankAdminUser, BankRecord } from "@/lib/bank-db";
import type {
  LetterOfCreditRecord,
  RiskAlertRecord,
  SettlementRecord,
  TradeContractRecord,
} from "@/lib/bank-operations-db";
import type {
  ClientAccountRecord,
  InternalUserRecord,
  RbacPolicyRecord,
} from "@/lib/bank-tenant-db";
import type { JsonDatabase } from "@/lib/json-db/schema";

function seedBanks(now: string): BankRecord[] {
  const base = (
    partial: Partial<BankRecord> &
      Pick<
        BankRecord,
        "id" | "slug" | "legalName" | "displayName" | "licenseNumber" | "status" | "adminUser"
      >,
  ): BankRecord => ({
    legalName: partial.legalName,
    licenseNumber: partial.licenseNumber,
    taxIdentificationNumber: "0000000000",
    headOfficeCity: "Addis Ababa",
    regulatorStatus: "licensed",
    dataResidencyRegion: "Ethiopia / Addis Ababa DC",
    displayName: partial.displayName,
    logoUrl: "",
    supportedCommodities: "Coffee, sesame, pulses",
    supportedCurrencies: "ETB, USD, EUR",
    primaryContactEmail: "tradefinance@bank.et",
    branchesEnabled: "Main, Bole",
    tradeFinanceContact: "+251 11 000 0000",
    documents: {
      bankingLicense: true,
      incorporation: true,
      boardResolution: true,
      apiSecurityQuestionnaire: true,
      authorizedSignatoryList: true,
      amlCftPolicy: true,
    },
    apiEnvironment: "sandbox",
    clientIdPrefix: partial.slug,
    credentialScopes: "lc:issue, guarantee:read, settlement:release",
    id: partial.id,
    slug: partial.slug,
    status: partial.status,
    adminUser: partial.adminUser,
    nextTask: "",
    credentials: partial.credentials ?? [],
    createdAt: now,
    updatedAt: now,
  });

  const banks = [
    base({
      id: "bank-abay",
      slug: "abay",
      legalName: "Abay Bank Share Company",
      displayName: "Abay Bank",
      licenseNumber: "NBE-BNK-0001",
      status: "active",
      adminUser: "Mekdes Alemu",
      credentials: [
        {
          id: "cred-abay-prod",
          clientId: "abay-corebanking-prod",
          environment: "production",
          scopes: "lc:issue, guarantee:read, settlement:release",
          status: "active",
          createdAt: now,
        },
      ],
    }),
    base({
      id: "bank-dashen",
      slug: "dashen",
      legalName: "Dashen Bank Share Company",
      displayName: "Dashen Bank",
      licenseNumber: "NBE-BNK-0002",
      status: "pending_review",
      adminUser: "Pending",
    }),
    base({
      id: "bank-awash",
      slug: "awash",
      legalName: "Awash Bank Share Company",
      displayName: "Awash Bank",
      licenseNumber: "NBE-BNK-0003",
      status: "active",
      adminUser: "Hana Bekele",
      credentials: [
        {
          id: "cred-awash-sandbox",
          clientId: "awash-lc-sandbox",
          environment: "sandbox",
          scopes: "lc:issue, guarantee:read",
          status: "sandbox",
          createdAt: now,
        },
      ],
    }),
  ];

  return banks.map((bank) => ({
    ...bank,
    nextTask:
      bank.status === "pending_review"
        ? "Verify license and approve bank"
        : bank.adminUser === "Pending"
          ? "Create Bank Admin user"
          : "Review platform controls",
  }));
}

function seedBankAdmins(now: string): BankAdminUser[] {
  return [
    {
      id: "admin-abay",
      fullName: "Mekdes Alemu",
      workEmail: "bank.admin@abaybank.et",
      mobileNumber: "+251 911 000 001",
      username: "bank.admin",
      bankId: "bank-abay",
      primaryBranch: "Head Office",
      role: "BANK_ADMIN",
      permissions: {
        manageBankProfile: true,
        manageBankUsers: true,
        manageClientsAndLimits: true,
        viewAuditLogs: true,
      },
      status: "active",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "admin-awash",
      fullName: "Hana Bekele",
      workEmail: "admin@awashbank.et",
      mobileNumber: "+251 911 000 002",
      username: "awash.admin",
      bankId: "bank-awash",
      primaryBranch: "Head Office",
      role: "BANK_ADMIN",
      permissions: {
        manageBankProfile: true,
        manageBankUsers: true,
        manageClientsAndLimits: true,
        viewAuditLogs: true,
      },
      status: "active",
      createdAt: now,
      updatedAt: now,
    },
  ];
}

function seedClients(now: string): ClientAccountRecord[] {
  const emptyChecks = {
    businessLicense: false,
    taxCertificate: false,
    beneficialOwnershipDoc: false,
    sanctionsScreening: false,
    pepAdverseMedia: false,
    sourceOfFunds: false,
  };
  const emptyVerification = {
    kycDocumentsComplete: false,
    collateralReviewed: false,
    creditExposureApproved: false,
    complianceSignOffComplete: false,
  };

  return [
    {
      id: "client-nordic",
      bankId: "bank-abay",
      legalName: "Nordic Imports B.V.",
      traderType: "buyer",
      registrationTaxId: "NL-123456",
      relationshipManager: "Daniel Tadesse",
      kycStatus: "active",
      riskRating: "medium",
      eddNotes: "",
      permittedCommodities: "Coffee",
      beneficialOwner: "Nordic Holdings B.V.",
      jurisdiction: "Netherlands",
      contactEmail: "",
      preferredBank: "Abay Bank",
      documentChecks: { ...emptyChecks, businessLicense: true, taxCertificate: true },
      verificationDecision: "",
      verificationNotes: "",
      verificationChecklist: emptyVerification,
      edd: {
        beneficialOwnership: true,
        sanctionsScreening: true,
        pepAdverseMedia: true,
        sourceOfFunds: true,
        tradeHistory: true,
        complianceSignOff: true,
      },
      dailyLimit: "USD 1,000,000",
      perTradeLimit: "USD 250,000",
      totalExposureLimit: "USD 5,000,000",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "client-kaffa",
      bankId: "bank-abay",
      legalName: "Kaffa Trading PLC",
      traderType: "seller",
      registrationTaxId: "ET-778899",
      relationshipManager: "Mekdes Alemu",
      kycStatus: "active",
      riskRating: "low",
      eddNotes: "",
      permittedCommodities: "Coffee, sesame",
      beneficialOwner: "Kaffa Group",
      jurisdiction: "Ethiopia",
      contactEmail: "",
      preferredBank: "Abay Bank",
      documentChecks: emptyChecks,
      verificationDecision: "",
      verificationNotes: "",
      verificationChecklist: emptyVerification,
      edd: {
        beneficialOwnership: true,
        sanctionsScreening: true,
        pepAdverseMedia: false,
        sourceOfFunds: true,
        tradeHistory: true,
        complianceSignOff: true,
      },
      dailyLimit: "USD 500,000",
      perTradeLimit: "USD 150,000",
      totalExposureLimit: "USD 2,500,000",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "client-gulf",
      bankId: "bank-abay",
      legalName: "Gulf Coffee DMCC",
      traderType: "buyer",
      registrationTaxId: "AE-445566",
      relationshipManager: "Solomon Tesfaye",
      kycStatus: "pending",
      riskRating: "high",
      eddNotes: "EDD review in progress",
      permittedCommodities: "Coffee",
      beneficialOwner: "Gulf Coffee Holdings",
      jurisdiction: "UAE",
      contactEmail: "",
      preferredBank: "Abay Bank",
      documentChecks: { ...emptyChecks, beneficialOwnershipDoc: true },
      verificationDecision: "",
      verificationNotes: "",
      verificationChecklist: emptyVerification,
      edd: {
        beneficialOwnership: true,
        sanctionsScreening: false,
        pepAdverseMedia: false,
        sourceOfFunds: false,
        tradeHistory: false,
        complianceSignOff: false,
      },
      dailyLimit: "Manual review",
      perTradeLimit: "Manual review",
      totalExposureLimit: "Manual review",
      createdAt: now,
      updatedAt: now,
    },
  ];
}

function seedPlatformUsers(now: string): PlatformUserRecord[] {
  return [
    {
      id: "usr-super-admin",
      name: "Ankuaru Super Admin",
      email: "admin@ankuaru.com",
      role: "SUPER_ADMIN",
      roleLabel: "Ankuaru Super Admin",
      initials: "SA",
      dashboardTitle: "Global System Dashboard",
      dashboardSubtitle: "Banks, markets, platform risk, and network operations.",
      welcome: "Welcome back, Super Admin",
      defaultSection: "portfolio",
      taskHint: "Register banks, create Bank Admin users, and review platform controls.",
      status: "active",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "usr-bank-admin",
      name: "Mekdes Alemu",
      email: "bank.admin@abaybank.et",
      role: "BANK_ADMIN",
      roleLabel: "Bank Admin",
      bankName: "Abay Bank",
      initials: "MA",
      dashboardTitle: "Bank Management Dashboard",
      dashboardSubtitle: "Users, clients, guarantees, exposure, and settlement tasks.",
      welcome: "Welcome back, Bank Admin",
      defaultSection: "portfolio",
      taskHint: "Manage internal users, client trader accounts, RBAC, and pending LC approvals.",
      status: "active",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "usr-bank-onboarder",
      name: "Daniel Tadesse",
      email: "onboarder@abaybank.et",
      role: "BANK_ONBOARDER",
      roleLabel: "Bank Onboarder / Relationship Manager",
      bankName: "Abay Bank",
      initials: "DT",
      dashboardTitle: "Client Onboarding Dashboard",
      dashboardSubtitle: "KYC cases, document collection, and client readiness.",
      welcome: "Welcome back, Bank Onboarder",
      defaultSection: "portfolio",
      taskHint: "Complete KYC tasks and respond to document requests.",
      status: "active",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "usr-bank-verifier",
      name: "Hana Bekele",
      email: "verifier@abaybank.et",
      role: "BANK_VERIFIER",
      roleLabel: "Bank Verifier / Credit Officer",
      bankName: "Abay Bank",
      initials: "HB",
      dashboardTitle: "LC Approval & Verification Dashboard",
      dashboardSubtitle: "Pending LC requests, collateral review, and issuance actions.",
      welcome: "Welcome back, Bank Verifier",
      defaultSection: "portfolio",
      taskHint: "Review LC requests and issue digital guarantees.",
      status: "active",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "usr-client",
      name: "Nordic Imports B.V.",
      email: "buyer@nordic.example",
      role: "CLIENT",
      roleLabel: "Client Buyer",
      initials: "NI",
      dashboardTitle: "Trading Dashboard",
      dashboardSubtitle: "Market, portfolio, orders, and guarantee requests.",
      welcome: "Welcome back, Client",
      defaultSection: "portfolio",
      taskHint: "Track orders, portfolio lots, and bank-backed guarantees.",
      status: "active",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "usr-regulator",
      name: "Regulator Viewer",
      email: "regulator@ethiopia.gov.et",
      role: "REGULATOR",
      roleLabel: "Regulator (Read Only)",
      initials: "RG",
      dashboardTitle: "Regulator Read-Only Dashboard",
      dashboardSubtitle: "Audit trail, risk summaries, and market oversight reports.",
      welcome: "Welcome back, Regulator",
      defaultSection: "settlement",
      taskHint: "Review reports, audit trails, and DvP status.",
      status: "active",
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function createDefaultDatabase(): JsonDatabase {
  const now = new Date().toISOString();

  return {
    banks: seedBanks(now),
    bankAdmins: seedBankAdmins(now),
    platformUsers: seedPlatformUsers(now),
    internalUsers: [
      {
        id: "staff-hana",
        bankId: "bank-abay",
        fullName: "Hana Bekele",
        workEmail: "verifier@abaybank.et",
        branchDesk: "Trade Finance · Head Office",
        role: "BANK_VERIFIER",
        approvalLimit: "USD 250,000",
        commodityScope: "Coffee, sesame",
        effectiveFrom: "2024-03-01",
        permissions: {
          viewClients: true,
          createKycCase: false,
          reviewLcRequests: true,
          issueGuarantees: true,
          verifyBlockchainRecords: true,
          configureRiskRules: false,
          exportAuditReports: false,
        },
        status: "active",
        createdAt: now,
        updatedAt: now,
      },
    ],
    clients: seedClients(now),
    rbacPolicies: [
      {
        id: "rbac-verifier",
        bankId: "bank-abay",
        role: "BANK_VERIFIER",
        branchScope: "All branches",
        approvalThreshold: "USD 250,000",
        permissions: {
          clientOnboardingKyc: false,
          lcRequestReview: true,
          guaranteeIssuance: true,
          blockchainVerification: true,
          riskRuleConfiguration: false,
          settlementReleaseApproval: false,
          auditExport: false,
        },
        status: "published",
        createdAt: now,
        updatedAt: now,
      },
    ],
    lettersOfCredit: [
      {
        id: "lc-1",
        bankId: "bank-abay",
        applicant: "Nordic Imports B.V.",
        beneficiary: "Kaffa Trading PLC",
        lcType: "sight",
        amount: "USD 250,000",
        contractUid: "CTR-2026-00091",
        expiryDate: "2026-12-31",
        collateralReference: "Blocked deposit ABY-001",
        pdfTemplate: "NBE compliant LC template v1",
        lcUid: "LC-ABY-2026-0091",
        status: "issued",
        createdAt: now,
        updatedAt: now,
      },
    ],
    tradeContracts: [
      {
        id: "contract-1",
        bankId: "bank-abay",
        buyer: "Nordic Imports B.V.",
        seller: "Kaffa Trading PLC",
        guaranteeLcUid: "LC-ABY-2026-0091",
        contractType: "Coffee export sale · FOB Djibouti",
        commodity: "Ethiopian coffee · Jimma G5",
        quantity: "17.8t",
        price: "USD/kg differential",
        settlementTrigger: "Warehouse + BL confirmation",
        contractUid: "CTR-2026-00091",
        status: "anchored",
        blockchain: {
          network: "ANKUARU Permissioned Ledger",
          smartContract: "0xANK8F2A1C9D4E7B6A3F1C0D8E5B2A94F7ABAY",
          txHash:
            "0x91c4e7f2a8b3d601945fe2ac73b8d4e1f0a6c9b2d5e8f1a4c7b0d3e6f9a2c5",
          blockNumber: 18291437,
          documentHash:
            "0x4f8a2c91d7e6b3059481f2ac73d8e4b1c0a695f2e8d1a4c7b3e6f9a2c5d8e1",
          anchoredAt: now,
        },
        createdAt: now,
        updatedAt: now,
      },
    ],
    settlements: [
      {
        id: "settle-1",
        bankId: "bank-abay",
        contractUid: "CTR-2026-00091",
        buyer: "Nordic Imports B.V.",
        seller: "Kaffa Trading PLC",
        amount: "USD 250,000",
        status: "pending",
        trigger: "Await delivery confirmation",
        updatedAt: now,
      },
    ],
    riskAlerts: [
      {
        id: "risk-1",
        bankId: "bank-abay",
        clientName: "Gulf Coffee DMCC",
        commodity: "Coffee",
        exposure: "USD 1.2m",
        severity: "high",
        status: "open",
        message: "High-risk client pending EDD completion",
        updatedAt: now,
      },
    ],
  };
}
